### ISSUE TITLE
Unable to do RX/TX - RX Setup takes long time

### ISSUE THREAD

**Issue by ryan-dsouza** [ComThings/PandwaRF#26] opened 2017-10-25 15:42 UTC
Bluetooth connects fine. However unable to receive an RF signals as RX setup seems to go on forever. 
Attached logs
Phone is MotoG
Android ver 5.1

Tried with smaller buffer lengths. Any help will be appreciated.

PandwaRF Device Information:
MAC Address:                  E6:C2:E5:4B:62:6C
FW CC1111 Commit Id:          
FW CC1111 Version:            1.0.17
FW Nordic Commit Id:          
FW Nordic Version:            0.9.17

PandwaRF App Information:
APPLICATION_ID:               com.comthings.pandwarf
BUILD_TYPE:                   release
FLAVOR:                       pub
VERSION_CODE:                 10254
VERSION_NAME:                 1.2.54
App Commit Id:                b877d29
Gollum Android Lib Version:   0.7.17-pub-release
Gollum Android Lib Commit Id: b877d29
Gollum Device Lib Version:    0.0.7-pub-release
Gollum Device Lib Commit Id:  e340293
Gollum Device Lib Flavor:     e340293

Phone Information:
serial:                    TA9290DPBV
bootloader:                0x411A
manufacturer:              motorola
brand:                     motorola
hardware:                  qcom
board:                     MSM8226
device:                    falcon_umts
model:                     XT1032
display:                   LPB23.13-56
id:                        LPB23.13-56
type:                      user
user:                      hudsoncm
host:                      ilclbld36
fingerprint:               motorola/falcon_retgb/falcon_umts:5.1/LPB23.13-56/60:user/release-keys
tags:                      release-keys
time:                      1439854829000
radio firmware:            MSM8626BP_1032.3116.98.00R EMEA_CUST
version.codename:          REL
version.release:           5.1
version.incremental:       60
version.sdk_int:           22
Hash: cd8403413815ca03f9abc46ebfba33a7[
[logcat.zip](https://github.com/ComThings/PandwaRF/files/1415205/logcat.zip)
](url)

**Comment by trollwookiee** [comment] 2017-10-25 16:02
Hi, can you enable Dev Mode and go to CC1111 RF page ?
Then click on Read all.
Are registers returned ?

**Comment by ryan-dsouza** [comment] 2017-10-25 16:03
Yes I did that - None of the registers are returned - the page is blank

**Comment by rfenthusiast** [comment] 2017-10-25 16:19
![screenshot_2017-10-25-16-27-22](https://user-images.githubusercontent.com/33090583/32010046-9bf669d6-b9a8-11e7-9ef8-7c682fd79a80.png)

**Comment by ryan-dsouza** [comment] 2017-10-25 16:22
In the log file the functions are called getC1111RfRegisters and getC1111RfRegisters done.

**Comment by ryan-dsouza** [comment] 2017-10-25 16:22
![screenshot_2017-10-25-16-27-22](https://user-images.githubusercontent.com/18256001/32010199-0fa433ea-b9a9-11e7-8a12-42e629ff15c6.png)

**Comment by trollwookiee** [comment] 2017-10-25 17:55
I looked at the trace, the RF link seems dead:
cc1111_ReadReg: Error, peek returned null
rfsub1g_cc1111_Rf_GetMdmDRate: Failed, readburst returned null
...

Also I don't know the cause since I don't have the beginnign of the connection.
I suggest that you:

1. physically reset the PandwaRF
2. kill the Android app
3. restart the app and connect to PandwaRF
4. don't do RX capture, but go directly to CC1111 RF and try to read registers
5. send me the logcat debug trace.

thanks

**Comment by ryan-dsouza** [comment] 2017-10-25 18:21
Thanks for the quick response - Suspected the RF  ( seems to be the same problem on another 
device as well - Not sure what caused it - It did work a few times). 
------------------
[logcat-1.zip](https://github.com/ComThings/PandwaRF/files/1415719/logcat-1.zip)

PandwaRF Device Information:
MAC Address:                  E6:C2:E5:4B:62:6C
FW CC1111 Commit Id:          
FW CC1111 Version:            1.0.17
FW Nordic Commit Id:          
FW Nordic Version:            0.9.17

PandwaRF App Information:
APPLICATION_ID:               com.comthings.pandwarf
BUILD_TYPE:                   release
FLAVOR:                       pub
VERSION_CODE:                 10254
VERSION_NAME:                 1.2.54
App Commit Id:                b877d29
Gollum Android Lib Version:   0.7.17-pub-release
Gollum Android Lib Commit Id: b877d29
Gollum Device Lib Version:    0.0.7-pub-release
Gollum Device Lib Commit Id:  e340293
Gollum Device Lib Flavor:     e340293

Phone Information:
serial:                    TA9290DPBV
bootloader:                0x411A
manufacturer:              motorola
brand:                     motorola
hardware:                  qcom
board:                     MSM8226
device:                    falcon_umts
model:                     XT1032
display:                   LPB23.13-56
id:                        LPB23.13-56
type:                      user
user:                      hudsoncm
host:                      ilclbld36
fingerprint:               motorola/falcon_retgb/falcon_umts:5.1/LPB23.13-56/60:user/release-keys
tags:                      release-keys
time:                      1439854829000
radio firmware:            MSM8626BP_1032.3116.98.00R EMEA_CUST
version.codename:          REL
version.release:           5.1
version.incremental:       60
version.sdk_int:           22
Hash: ded54cd88a17ecfa228df53a3f02c4bb

**Comment by ryan-dsouza** [comment] 2017-10-25 18:22
The reset button in super cool by the way!

**Comment by ryan-dsouza** [comment] 2017-10-29 09:00
Any clues from the log @trollwookiee ?

**Comment by trollwookiee** [comment] 2017-10-30 07:46
I am trying to reproduce on a Moto G, Android 5.1 now.
Will keep you posted.
What is the fail rate ? Do you manage to get some data or never works ?

**Comment by ryan-dsouza** [comment] 2017-10-30 08:04
It worked for a few times on a Moto G, Android 4.4 - Until I ran into this error. Having the same error on 2 hardware units.
I updated the Android version 5.1 on the Moto G to see if it was an Android related issue. Still no luck.
I have tried it with a new Google Pixel, with Android 7.1 - Same problem.

**Comment by ryan-dsouza** [comment] 2017-10-30 19:39
Is it possible to download an older version of the Android app ?

**Comment by trollwookiee** [comment] 2017-10-31 07:55
Do you remember on what version it used to work ?

**Comment by ryan-dsouza** [comment] 2017-10-31 08:28
One before the 20th October one.

**Comment by trollwookiee** [comment] 2017-10-31 09:31
I just sent you an email with v1.2.53 from Oct 17.
Please check if it works better.

**Comment by ryan-dsouza** [comment] 2017-10-31 09:44
Hi @trollwookiee I tried downloading the latest app released on 27th - I am able to read the registers do RX/TX. So there definitely seems to be an issue with 1.2.54 (Oct 20th).

**Comment by trollwookiee** [comment] 2017-10-31 09:47
latest app released on 27th or 17th ?

- v1.2.55 has been release **27th** Oct
- v1.2.53 has been release **17th** Oct

v1.2.53 is ok ?

**Comment by ryan-dsouza** [comment] 2017-10-31 09:52
I didnt actually receive your email with 1.2.53. I tried on the latest one 1.2.55 (On both Moto G and Google Pixel)

**Comment by trollwookiee** [comment] 2017-10-31 09:56
I used email you gave us when you ordered on pandwarf.com

**Comment by trollwookiee** [comment] 2017-10-31 09:57
anyway thanks for feedback.
Enjoy your new toy :-)

**Comment by ryan-dsouza** [comment] 2017-10-31 09:58
oh ok. Got it - It was in spam. Will test it and give feedback

**Comment by ryan-dsouza** [comment] 2017-10-31 16:35
Hi @trollwookiee  - Seems like this issue is intermittent now. I tried reflashing the hardware via support recovery and it works the first time around with the latest firmware and android app.

Whenever RX setup and RX works, it displays the C1111 bootloader version in FW menu. After few times of receiving the signals,  RX stops working. The C1111 bootloader version is usually displayed as Unknown in those circumstances ( Attached screenshots and debug trace). Might be easier to read the debug trace from the reverse . 

Any help is appreciated. 
--------------------------------


PandwaRF Device Information:
MAC Address:                  F2:14:AB:37:92:D9
FW CC1111 Commit Id:          
FW CC1111 Version:            1.0.17
FW Nordic Commit Id:          
FW Nordic Version:            0.9.17

PandwaRF App Information:
APPLICATION_ID:               com.comthings.pandwarf
BUILD_TYPE:                   release
FLAVOR:                       pub
VERSION_CODE:                 10255
VERSION_NAME:                 1.2.55
App Commit Id:                cb47233
Gollum Android Lib Version:   0.7.18-pub-release
Gollum Android Lib Commit Id: cb47233
Gollum Device Lib Version:    0.0.7-pub-release
Gollum Device Lib Commit Id:  4423715
Gollum Device Lib Flavor:     4423715

Phone Information:
serial:                    TA9290DPBV
bootloader:                0x411A
manufacturer:              motorola
brand:                     motorola
hardware:                  qcom
board:                     MSM8226
device:                    falcon_umts
model:                     XT1032
display:                   LPB23.13-56
id:                        LPB23.13-56
type:                      user
user:                      hudsoncm
host:                      ilclbld36
fingerprint:               motorola/falcon_retgb/falcon_umts:5.1/LPB23.13-56/60:user/release-keys
tags:                      release-keys
time:                      1439854829000
radio firmware:            MSM8626BP_1032.3116.98.00R EMEA_CUST
version.codename:          REL
version.release:           5.1
version.incremental:       60
version.sdk_int:           22
Hash: 0107212373046f49d3cd8371af8d8550
 
[logcat.zip](https://github.com/ComThings/PandwaRF/files/1431475/logcat.zip)

![screenshot_2017-10-31-15-59-05](https://user-images.githubusercontent.com/18256001/32235973-d02bc49e-be58-11e7-9f05-1eea5369defe.png)
![screenshot_2017-10-31-16-00-11](https://user-images.githubusercontent.com/18256001/32235983-d65b59f6-be58-11e7-88e8-769fbc997935.png)

**Comment by trollwookiee** [comment] 2017-11-08 08:19
Shall be fixed in Android V1.2.57.

**Closed by trollwookiee** 2017-11-08 08:19 UTC
Labels: bug

**Comment by ryan-dsouza** [comment] 2017-11-08 08:32
Many thanks !
